### ISSUE TITLE
Mysterious "heap out of memory"

### ISSUE THREAD

**Issue by gibboa** [gibboa/Open_IO#18]
commonly get a heap runs out of memory error on node, possibly related to the convertFunction but I'm not sure why

**Comment by drochecsp2017** [comment]
[error_report.txt](https://github.com/gibboa/Open_IO/files/3081945/error_report.txt)
Linked is the error thrown in console when the above issue occurs. Going to try fixing it, see how it goes.

**Comment by gibboa** [comment]
Believe its fixed, Its hard to test all possibilities, please reopen issue if it comes up again
