### ISSUE TITLE
Server crashes if collision on boost

### ISSUE THREAD

**Issue by zacknawrocki** [gibboa/Open_IO#29]
To repeat, collide into a boundary, while holding down space bar (while using boost).

<img width="562" alt="Screen Shot 2019-04-18 at 7 40 38 PM" src="https://user-images.githubusercontent.com/40272327/56397588-79912700-6212-11e9-92f7-fa0e510d0658.png">

**Comment by gibboa** [comment]
fixed... we werent checking if players actually existed before applying their inputs
